### ISSUE TITLE
载入小组件失败

### ISSUE THREAD

**Issue by YmmLom** [xluu233/Widget12#1]
#### 设备
名称: Pixel_2_API_21 
CPU/ABI: Intel Atom (x86) 
Target: default [] (API 级别 21) 
外观: pixel_2 
SD 卡: 512M

**Comment by xluu233** [comment]
加载失败一般是由于引入了不支持的控件，请查看RemoteView支持的控件列表

**Comment by YmmLom** [comment]
> 加载失败一般是由于引入了不支持的控件，请查看RemoteView支持的控件列表

感谢大佬回复,`CheckBox`要API 31才支持,删除后能正常载入
我在开发本校的课程表, (市场上的功能繁多,广告横行), 大佬多多指教
